# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sshgrpc.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsshgrpc.proto\x12\x08sshgrpcs\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2M\n\x0e\x45xampleService\x12;\n\x08SayHello\x12\x16.sshgrpcs.HelloRequest\x1a\x17.sshgrpcs.HelloResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sshgrpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=27
  _globals['_HELLOREQUEST']._serialized_end=55
  _globals['_HELLORESPONSE']._serialized_start=57
  _globals['_HELLORESPONSE']._serialized_end=89
  _globals['_EXAMPLESERVICE']._serialized_start=91
  _globals['_EXAMPLESERVICE']._serialized_end=168
# @@protoc_insertion_point(module_scope)
